### ISSUE TITLE
/tmp/aconfmgr-$USER is created with world-readable permissions

### ISSUE THREAD

**Issue by joanbm** [CyberShadow/aconfmgr#107]
When installed system-wide, running `aconfmgr save` will create a directory in `/tmp/aconfmgr-$USER` containing various files (including copies of any stray files and files marked with `CopyFile`).

However, this directory `/tmp/aconfmgr-$USER` is created with the default permissions from `mkdir -p` (usually mode=0755), which makes the directory readable for any user in the system. Files which are usually only readable by root such as `/etc/crypttab` are copied there with world-readable-permissions.

Example:

```sh
$ ls -lah /tmp/ | grep aconfmgr
$ aconfmgr save
[...]
$ ls -lah /tmp/ | grep aconfmgr
drwxr-xr-x  4 zealcharm zealcharm 160 Jul 27 20:30 aconfmgr-zealcharm
$ sudo -u nobody cat /tmp/aconfmgr-zealcharm/system/files/etc/crypttab
[...]
# Configuration for encrypted block devices.
# See crypttab(5) for details.
# crypttab: mappings for encrypted partitions
[...]
```

The directory should be created with more limited permissions (e.g. mode=0700) to avoid other users in the system from reading the contents.

**Comment by CyberShadow** [comment]
Thanks for filing this. I didn't notice this because of my umask setting.

**Comment by joanbm** [comment]
Nice, I just went to take a walk outside and it's already fixed when I go back ;) Thank you very much!

**Comment by joanbm** [comment]
Hmmm, I actually tried the commit, and it doesn't work for the case I used in the example `aconfmgr save`.

This line in `AconfCompileOutput`:
```
mkdir --parents "$output_dir"
```

Runs before the line you changed in `AconfCompileSystem`, and `output_dir="$tmp_dir"/output`.

**Comment by CyberShadow** [comment]
Yep, I need to sit down and do this properly, with a test etc.

**Comment by CyberShadow** [comment]
> EDIT: As far as I can tell, all actions (apply/save/check/diff) use or can use the temporary directory, so it should be safer to create it at program start instead of trying to to track and fix all potential `mkdir --parents` usages.

I didn't want to do it that way because it was difficult to test in the way that the test suite works currently. There was no "single entry point" that was used by both the test suite and aconfmgr's normal execution flow.

I also needed to move the temporary directory used for building AUR packages outside the main temporary directory, as the makepkg user ("nobody") no longer could access paths under the latter.

**Comment by joanbm** [comment]
I repeated a quick test with all 4 aconfmgr commands and it looks like the folder is created with the right permissions now. Thanks!
