### ISSUE TITLE
Inline fstab entry without saving or overwriting genfstab-generated portion?

### ISSUE THREAD

**Issue by burrhole** [CyberShadow/aconfmgr#116]
Hi there, I'm getting aconfmgr set up on a couple of machines, and I'm running into a bit of an issue: I have a network share set up with sshfs that I'd like to add to my template, but I'm not sure how best to inline that without affecting the portion set up with genfstab.
I've tried the "Ignoring parts of files" style approach with 
```
function fstabfilter(){
       grep -v -e 'UUID' -e '^\#' -e '^$'
}
AddFileContentFilter '/etc/fstab' fstabfilter
```
Which does work to save only the sshfs entry, but proceeds to overwrite everything except the sshfs entry on `aconfmgr apply`, and the "Inlining file edits" approach seems to only be able to append an edit to the original package's file, which also wouldn't be ideal since it would also discard the other entries.
There could be something obvious I'm missing but I'm currently at a loss.

Thank you for your time

**Comment by CyberShadow** [comment]
Thanks, appreciated!

Closing the issue but feel free to follow up.
