### ISSUE TITLE
factoring out base group?

### ISSUE THREAD

**Issue by Dieterbe** [CyberShadow/aconfmgr#125]
the below factors out the base group package installation.
I wonder if it would make sense for aconfmgr to do this automatically?
Alternatively, all the individual packages could even be replaced by installation of just 'base', but that might be dangerous.. future versions of 'base' may not include the same set of packages.
```
#!/bin/bash
cd ~/.config/aconfmgr
for i in $(pacman -Si base | grep '^Depends On' | sed 's/.*://'); do 
  grep "^AddPackage $i " 99-unsorted.sh >> 01-base.sh
  sed -i "/^AddPackage $i /d" 99-unsorted.sh
done
```

**Comment by CyberShadow** [comment]
> I wonder if it would make sense for aconfmgr to do this automatically?

I don't think so, as Arch does not actually require all the packages in `base` to be installed; I think it's more of a preset of what to install on a new system.

> Alternatively, all the individual packages could even be replaced by installation of just 'base', but that might be dangerous.. future versions of 'base' may not include the same set of packages.

Yes, but we do have the `AddPackageGroup` helper for those who wish to do this anyway (see #29).
