### ISSUE TITLE
Problem with sudo in combination with fingerprint reader

### ISSUE THREAD

**Issue by poleprogger** [CyberShadow/aconfmgr#14]
: Collecting data...
:: Compiling user configuration...
::: Using configuration in /home/mj/.config/aconfmgr
::: Sourcing /home/mj/.config/aconfmgr/10-ignore.sh...
::: Done (0 native packages, 0 foreign packages, 0 files).
:: Inspecting system state...
::: Querying package list...
:::: Done.
::: Enumerating managed files...
:::: Done.
::: Searching for lost files...
:::: Done (426 lost files).
::: Searching for modified files...
........
:::: Done (39 modified files).
::: Reading file attributes...
:::: Reading file types...
stat: cannot stat 'Swipe your finger across the fingerprint reader': No such file or directory
:::: Fatal error! Stack trace:
::::: /usr/lib/aconfmgr/common.bash:1 [AconfCompileSystem]
::::: /usr/lib/aconfmgr/common.bash:452 [AconfCompile]
::::: /usr/lib/aconfmgr/save.bash:9 [AconfSave]
::::: /usr/bin/aconfmgr:164 [Main]
::::: /usr/bin/aconfmgr:178 [main]

The message "Swipe your finger across the fingerprint reader" normally appears when i run sudo. So this error does not happen when i run sudo before the 'aconfmgr save' command.

**Comment by CyberShadow** [comment]
Hmm... that might be a bug in the PAM module or whatever is outputting the message. I believe it should be printed to stderr, whereas it is being printed to stdout. For example, the usual password prompt message is printed to stderr.

Do you know what component that message comes from?

**Comment by poleprogger** [comment]
The PAM module is called pam_fprintd.so and i have added it to 
/etc/pam.d/login
""/sudo 
with the following line: 
auth       sufficient   pam_fprintd.so

**Comment by CyberShadow** [comment]
I filed an issue in sudo's bugtracker:
https://bugzilla.sudo.ws/show_bug.cgi?id=895

Though, it seems unlikely that it will get a reply. Most issues filed there seem to be ignored.

**Comment by CyberShadow** [comment]
Well, this was actually fixed in `sudo`. :)
