### ISSUE TITLE
[Bug]: Insecure permissions for file copies

### ISSUE THREAD

**Issue by desbma** [CyberShadow/aconfmgr#142]
### General description of the problem:

Files stored in `~/.config/aconfmgr/files` by `aconfmgr save` use the default umask and are typically created with 644 permission mask.
As a result any secret on the system, for example `/etc/shadow` will be copied as world readable in `~/.config/aconfmgr/files/etc/shadow`.

### Steps to reproduce the problem:

1. Run `aconfmgr save`
2. Run `ls -l /etc/shadow && ls -l ~/.config/aconfmgr/files/etc/shadow` and see the permissions are less restrictive

### Expected result:

* `~/.config/aconfmgr/files` should be 700
* files in `~/.config/aconfmgr/files` should use the original permission mask

**Comment by CyberShadow** [comment]
Thanks for the report!

I have my home directory set to 700 and my umask at 027, but I realize this may not be the default or everyone's preference.
