### ISSUE TITLE
stack trace error during `apply` 

### ISSUE THREAD

**Issue by v1kn** [CyberShadow/aconfmgr#15]
==> Installing missing dependencies...
    error: target not found: pacli
    ==> ERROR: 'pacman' failed to install missing dependencies.
    :: fzf is a new orphan package
    :: failed to build bmenu package(s)
    :::: Fatal error! Stack trace:
    ::::: /usr/lib/aconfmgr/common.bash:1 [AconfInstallForeign]
    ::::: /usr/lib/aconfmgr/apply.bash:238 [AconfApply]
    ::::: /usr/bin/aconfmgr:167 [Main]
    ::::: /usr/bin/aconfmgr:178 [main]

After a `save` state, I uninstalled several native packages, and two foreign ones `pacli` and `bmenu`. re-installation of native packages was uneventful. Above error happened during foreign package re-installation.  

contents of `00-config.sh`:

    verbose=1
    prompt_mode=paranoid
    aur_helper=pacaur
    color=always

**Comment by CyberShadow** [comment]
It looks like the failure came from `pacaur`. The log excerpt does not have enough context to show what package `aconfmgr` was attempting to reinstall. I would suggest to check what package that is, and see if `pacaur` can install it by itself. (Perhaps `pacli` was moved to the AUR recently and `pacaur`'s cache is outdated?)

**Comment by v1kn** [comment]
You are right. I tried `pacaur` standalone and it failed. Tried `yaourt` standalone and it worked. I never had errors from `pacaur` till now. 

Thanks. I will close the issue
