### ISSUE TITLE
first run does not work with a swapfile

### ISSUE THREAD

**Issue by fallingcats** [CyberShadow/aconfmgr#172]
### General description of the problem:

The first run of aconfmgr it tried copying my swapfile to tmpfs which killed my open applications

### Steps to reproduce the problem:

1. Have swapfile at /swapfile
2. Run `aconfmgr save` for the first time

### Expected result:

Not running my system out of ram

### Log:

```text
::: Processing found files...
:::: Warning: copying large file /swapfile (12884901888 bytes). Add IgnorePath /swapfile to configuration to ignore.
cat: write error: No space left on device
:::: Fatal error! Stack trace:
::::: /usr/lib/aconfmgr/common.bash:620 [AconfCompileSystem]
::::: /usr/lib/aconfmgr/common.bash:901 [AconfCompile]
::::: /usr/lib/aconfmgr/save.bash:9 [AconfSave]
::::: /usr/lib/aconfmgr/main.bash:185 [Main]
::::: /usr/lib/aconfmgr/main.bash:205 [source]
::::: /bin/aconfmgr:26 [main]
:::: Probable cause: low disk space (0 bytes) in /tmp. Suggestions:
::::: - Ignore more files and directories using IgnorePath directives;
::::: - Free up more space in /tmp;
::::: - Set $TMPDIR to another location before invoking aconfmgr.
```

**Comment by CyberShadow** [comment]
Hi,

Kindly read https://github.com/CyberShadow/aconfmgr#first-run and the warning message printed in the log excerpt above.

Thank you.

**Comment by fallingcats** [comment]
> Hi,
> 
> Kindly read https://github.com/CyberShadow/aconfmgr#first-run and the warning message printed in the log excerpt above.
> 
> Thank you.

I did, but there isn't any warning in there that it will kill my open applications by copying everything into /tmp.

In any case it reads like "run it and see what happens, adjust config later" which is quite different from "you really ought to exclude enough so everything fits into ram or otherwise ..."

**Comment by CyberShadow** [comment]
Well, aconfmgr didn't kill your applications. I actually don't know why that happened. Are you running a daemon that cleans up files in `/tmp` when there is space pressure on that tmpfs?

It does seem unusual, considering that other users haven't run into this.

**Comment by CyberShadow** [comment]
Maybe the documentation can be clarified to make it clearer that it's OK to cancel an initial `save` if you suspect it's doing the wrong thing, and adjust ignore rules automatically.

We could also ignore swap files by default, but it's just one of many types of big files you don't want to include in your configuration, so I don't think this problem is really about swap files specifically.

**Comment by fallingcats** [comment]
> Well, aconfmgr didn't kill your applications. I actually don't know why that happened

It happened because copying multiple GiBs of swapfile into a tmpfs ran me out of ram and the oom killer kicked in.

**Comment by CyberShadow** [comment]
> It happened because copying multiple GiBs of swapfile into a tmpfs ran me out of ram and the oom killer kicked in.

Huh, that never happened to me before, even though I abuse my RAM and `/tmp` regularly. But I suppose it's something that can happen.

> Also copying from an SSD into ram isn't really slow enough that you can cancel when you see it.

That's fair.

The way I'm thinking of addressing it is to refuse performing the operation if it would exhaust free space in the target filesystem. We can do that by adding up file sizes before trying to copy any of them.

**Comment by CyberShadow** [comment]
https://github.com/CyberShadow/aconfmgr/pull/173
