### ISSUE TITLE
Support for journald

### ISSUE THREAD

**Issue by FrederikLauber** [CyberShadow/aconfmgr#18]
Hello,

I want to run aconfmgr as a systemd service and have its output put into my journal.
Unfortunate, this does not seem to work atm.

You can create a service file to start aconfmgr but the journal will only show
```Feb 08 17:13:14 Mika aconfmgr[29198]: [1.2K blob data]```
instead of the real output.
I already tried the --color Never option, does not help.

Thanks in advance!

**Comment by CyberShadow** [comment]
Hi, is it any better with 3ceb9d53dbfb80934699632314e1614e6a23c527?

**Comment by FrederikLauber** [comment]
That helped partially. 
I now see this: 
```
Feb 09 13:42:59 Mika aconfmgr[11597]: [635B blob data]
Feb 09 13:42:59 Mika aconfmgr[11597]: [1014B blob data]
Feb 09 13:42:59 Mika aconfmgr[11597]: :::: filesystem: /etc/group
Feb 09 13:42:59 Mika aconfmgr[11597]: :::: filesystem: /etc/gshadow
Feb 09 13:42:59 Mika aconfmgr[11597]: :::: filesystem: /etc/passwd
Feb 09 13:42:59 Mika aconfmgr[11597]: :::: filesystem: /etc/shadow
Feb 09 13:43:00 Mika aconfmgr[11597]: [610B blob data]
Feb 09 13:43:12 Mika aconfmgr[11597]: [1.3K blob data]
Feb 09 13:43:15 Mika aconfmgr[11597]: [2.0K blob data]
Feb 09 13:43:24 Mika aconfmgr[11597]: [2.0K blob data]
```

**Comment by CyberShadow** [comment]
OK, so it doesn't like carriage returns either. 7d1968d00a93cb0257edc4d34f4b412088908f5a should fix it.

**Comment by FrederikLauber** [comment]
Hi,

now all the text is displayed, thanks!
Maybe I will have to ask for an additional switch there only the packages are displayed which do contain a changed file. atm, all checked packages are listed twice like this:
```
Feb 09 16:30:21 Mika aconfmgr[3658]: :::: qt5-serialport...
Feb 09 16:30:21 Mika aconfmgr[3658]: :::: qt5-serialport...
Feb 09 16:30:21 Mika aconfmgr[3658]: :::: qt5-speech...
Feb 09 16:30:21 Mika aconfmgr[3658]: :::: qt5-speech...
```
