### ISSUE TITLE
aconfmgr snags after finishing backup - never returns to command line

### ISSUE THREAD

**Issue by pomomayu** [CyberShadow/aconfmgr#184]
### General description of the problem:

During the most recent system backup aconfmgr never closed out when it finishes. It never returns to the command line. See the log section below. This is where it stops. This did not happen during previous backups. There's nothing unique about way we use aconfmgr.

### Steps to reproduce the problem:

`$ ./aconfmgr --config ~/my/config save`

aconfmgr stops here:

### Configuration:

```bash
[mysys]$ uname -a
Linux myhost 6.6.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000 x86_64 GNU/Linux

 10-ignores.sh
   IgnorePath '/var/lib/pacman/local/*' # package metadata
   IgnorePath '/var/lib/pacman/sync/*.db' # repos
   IgnorePath '/var/lib/pacman/sync/*.db.sig' # repo sigs
```

### Expected result:

aconfmgr should finish!

### Log:

```text
`
::: Done (89703 only in system, 89 changed, 66 only in config).
:: Examining file properties...
::: Loading data...
:::: Done.
::: Comparing file properties...
:::: Done.
::: Done (184178 only in system, 0 changed, 102 only in config).
:: Done.
: Saving configuration...
:: Examining packages...
::: Done.
:: Registering files...
::: Found 66 extra files.
:::: Done.
::: Found 89703 new and 89 changed files.
`
```

**Comment by CyberShadow** [comment]
If you press Ctrl+C, do you get a stack trace with more information?

**Comment by pomomayu** [comment]
Hey made some adjustments and it worked on the second try. This time the system was rebooted, and the Chromium cache was added to 10-ignore.sh. Not sure if either of these were the root cause. Closing this for now.

In the previous attempt the system had just been updated with pacman -Syu. The system had not been rebooted before running aconfmgr, but I didn't think it would affect anything. And yes I was backing up my Chromium cache! I'm protective of the state of my browser hah.
