### ISSUE TITLE
[Question] Dealing with different file contents in multiple systems

### ISSUE THREAD

**Issue by nunocastromartins** [CyberShadow/aconfmgr#19]
Hi! First of all, excellent software! Thank you for your work!

I hope you can provide some insight on a question I have.
In the README, you provide a solution for having different packages for different systems:
```sh
AddPackage coreutils
# ... more common packages ...

if [[ "$HOST" == "home.example.com" ]]
then
	AddPackage nvidia
	AddPackage nvidia-utils
	# ... more packages only for the home system ...
fi
```

I wonder how you'd deal with having different content for the same file in different systems.
As an example, consider that you have two systems (`s1` and `s2`), each with a different `/etc/hosts`. Further suppose that you don't wish to have a different Git branch for each system.

My idea on how to solve this would be to have three folders where I store the files: `files` (the folder used by `aconfmgr`), `files-s1`, and `files-s2`. Then do something such as:

```sh
ln -sf "files-$HOST/etc/hosts" files/etc/hosts
CopyFile /etc/hosts
```

What do you think of this approach? I haven't tested it, would it work? How would you make it better? Any alternative ideas?

Another alternative would be for you to change `CopyFile` to allow distinct source/target paths; allowing me to have in the `files` directory a `etc/hosts-s1` and `etc/hosts-s2` and then do: `CopyFile "/etc/hosts-$HOST" /etc/hosts`.

In any case, I think the answer to this question should be added to the README; I don't think it is unreasonable for different systems to have different files.

Once again, thank you for your work!

**Comment by CyberShadow** [comment]
> First of all, excellent software!

Thanks!

> What do you think of this approach?

`CopyFile`, at least in its current implementation, will not follow symlinks, and will copy them as-is.

> How would you make it better?

As the README mentions, scripts don't need to be restricted to helper functions such as `CopyFile`, and may write to the output directories directly. In this case, the equivalent code would probably be:

```bash
mkdir --parents "$output_dir"/files/etc
cp "$config_dir"/files-$HOST/etc/hosts "$output_dir"/files/etc/hosts
```
> Any alternative ideas?

You can inline the file directly in your configuration. For example, here is how `/etc/hosts` is configured in my personal configuration:

```bash
# Hosts

f="$(GetPackageOriginalFile filesystem /etc/hosts)"
echo '89.28.117.31	home.thecybershadow.net' >> "$f" # Make 'hostname' instant when Internet is offline
if [[ "$HOSTNAME" == vaio.thecybershadow.net ]]
then
	echo '127.0.1.1	vaio.thecybershadow.net	vaio' >> "$f" # ditto
fi
echo '0.0.0.0	host.does.not.exist' >> "$f" # Work around emacs tramp lag
```

> Another alternative would be for you to change `CopyFile` to allow distinct source/target paths

`CopyFile` already has optional arguments to set the mode/owner, so it would probably need to be done as a new function. If it turns out it's a common request, I could add it, however you could also define your personal helper functions as part of your configuration as well.

> In any case, I think the answer to this question should be added to the README; I don't think it is unreasonable for different systems to have different files.

Good idea!

**Comment by nunocastromartins** [comment]
Thank you for your input!

The `hosts` file was just an example, others would be trickier to inline as they are altogether different.
All in all, I think I prefer having distinct files. I'll opt for the custom function approach and have everything inside the `files` directory, rather than a new directory for each system.

I adapted your `CopyFile` function; I'm in no condition to test this out right now (will have to do it later), but would the following work? I'd just have to place it in a file such as `00-helpers.sh`, correct?

```sh
function CopyRenameFile() {
	local input_file="$1"
        local output_file="$2"
	local mode="${3:-}"
	local owner="${4:-}"
	local group="${5:-}"

	mkdir --parents "$(dirname "$output_dir"/files/"$output_file")"

	cp --no-dereference \
	   "$config_dir"/files/"$input_file" \
	   "$output_dir"/files/"$output_file"

	SetFileProperty "$output_file" mode  "$mode"
	SetFileProperty "$output_file" owner "$owner"
	SetFileProperty "$output_file" group "$group"
}
```

Sorry to bother you! :-)

**Comment by CyberShadow** [comment]
> but would the following work?

Yes, I think it should work.

> I'd just have to place it in a file such as 00-helpers.sh, correct?

That's right.

> Sorry to bother you! :-)

No problem :)

**Comment by nunocastromartins** [comment]
Thank you for your help!
As a reference to someone who might come across this in the future, here's what I ended up with in a `00-helpers.sh`:
```sh
#
# CopyRenameFile PATH PATH [MODE [OWNER [GROUP]]]
#
# Copies a file from the "files" subdirectory to the output (renaming it first).
#
# The specified paths should be relative to the root of the "files"
# subdirectory.
#
# If MODE, OWNER and GROUP are unspecified, they default to
# "644", "root" and "root" respectively for new files.
#

function CopyRenameFile() {
  local input_file="$1"
  local output_file="$2"
  local mode="${3:-}"
  local owner="${4:-}"
  local group="${5:-}"

  mkdir --parents "$(dirname "$output_dir"/files/"$output_file")"

  cp --no-dereference\
    "$config_dir"/files/"$input_file"\
    "$output_dir"/files/"$output_file"

  SetFileProperty "$output_file" mode  "$mode"
  SetFileProperty "$output_file" owner "$owner"
  SetFileProperty "$output_file" group "$group"
}

#
# CopyHostFile PATH [MODE [OWNER [GROUP]]]
#
# Copies a file from the "files" subdirectory (with a `-$HOSTNAME` suffix) to the
# output.
#
# The specified path should be relative to the root of the "files" subdirectory.
#
# If MODE, OWNER and GROUP are unspecified, they default to
# "644", "root" and "root" respectively for new files.
#

function CopyHostFile() {
  local file_host="$1-$HOSTNAME"
  local file="$1"
  local mode="${2:-}"
  local owner="${3:-}"
  local group="${4:-}"
  
  if [ -f "$config_dir"/files/"$file_host" ]
  then
    CopyRenameFile "$file_host" "$file" "$mode" "$owner" "$group"
  fi
}
```

I'll leave the issue open, close it at your discretion (maybe after first adding the relevant info to the README).

Once again, awesome software! Thanks!

**Comment by CyberShadow** [comment]
> I'll leave the issue open, close it at your discretion (maybe after first adding the relevant info to the README).

Done. I decided to add a helper function like in your example, as the documentation would have been awkward without one, and it seems useful enough to have it as a standard one either way.

**Comment by nunocastromartins** [comment]
Awesome.
You're awesome!

**Comment by CyberShadow** [comment]
You're awesome too, @nunocastromartins. I wish more users of my software were more like you! :)
