### ISSUE TITLE
custom ignore_paths

### ISSUE THREAD

**Issue by benwbooth** [CyberShadow/aconfmgr#2]
I have some NFS volumes mounted outside of /mnt and /media. It would be great if there was a command line argument to add to ignore_paths so that those folders could be skipped when running `aconfmgr save`. 

Thanks!

**Comment by thenaterhood** [comment]
You can create a config file in your configuration directory that adds ignored paths. I have $config/10-ignores.sh which is a list of

```
IgnorePath /var/lib/....
IgnorePath /var/log
....
```

**Comment by CyberShadow** [comment]
As @thenaterhood already explained, the provided method of ignoring paths is using the `IgnorePath` helper function.

I added a mention of ignoring files to the "first run" section of the README in 4e14e695d335c2654d14d05da0734be205c4e696, which should hopefully resolve this issue.
