### ISSUE TITLE
aconfmgr cannot remove directory from backup?

### ISSUE THREAD

**Issue by FrederikLauber** [CyberShadow/aconfmgr#24]
Hi,

running into a strange issue here:
I deleted /boot/grub after I switched to systemd-boot.
Afterwards, aconfmgr did not work anymore due to this:

[foo@bar boot]$ /usr/bin/aconfmgr --color never save
: Collecting data...
:: Compiling user configuration...
::: Using configuration in /home/foo/.config/aconfmgr
::: Sourcing /home/foo/.config/aconfmgr/10-ignores.sh...
::: Sourcing /home/foo/.config/aconfmgr/99-unsorted.sh...
rm: das Entfernen von '/tmp/aconfmgr-foo/output/files//boot/grub' ist nicht möglich: Ist ein Verzeichnis
:::: Fatal error! Stack trace:
::::: /usr/lib/aconfmgr/helpers.bash:236 [RemoveFile]
::::: /home/foo/.config/aconfmgr/99-unsorted.sh:2860 [source]
::::: /usr/lib/aconfmgr/common.bash:100 [AconfCompileOutput]
::::: /usr/lib/aconfmgr/common.bash:713 [AconfCompile]
::::: /usr/lib/aconfmgr/save.bash:9 [AconfSave]
::::: /usr/lib/aconfmgr/main.bash:152 [Main]
::::: /usr/lib/aconfmgr/main.bash:169 [source]
::::: /usr/bin/aconfmgr:26 [main]

sorry for the German but it basically says that it cannot delete /tmp/aconfmgr-foo/output/files//boot/grub because it is a folder.

Did I do something wrong? Is deleting folders not supported in aconfmgr?

**Comment by CyberShadow** [comment]
There is an error in your configuration. You will need to update it to remove stale instances of `RemoveFile`.

From the function's documentation:

```bash
# Removes an earlier-added file.
#
# Emitted by `aconfmgr save` when a file is present in the configuration,
# but absent (or, in case of files owned by packages, unmodified) on the system.
#
# You should refactor out any occurrences of this function from your configuration.
```

**Comment by FrederikLauber** [comment]
Ah okay, sorry for the noise then.

I thought save would just save the current configuration by updating the existing one (and hence also remove stale files). Thanks for clarifying!

**Comment by CyberShadow** [comment]
There is definitely a bug or possible improvement in aconfmgr here, too. I've added a note to fix this.
