### ISSUE TITLE
Delete aconfmgr directory from /tmp when exiting

### ISSUE THREAD

**Issue by thenaterhood** [CyberShadow/aconfmgr#3]
The /tmp/aconfmgt-<user> directory doesn't get deleted when the program exits. Depending on the system, this can take up a fair amount of room (especially on the first run before all the necessary ignores are added).

**Comment by CyberShadow** [comment]
Deleting the directory automatically would interfere with the `--skip-inspection` step.

Isn't `/tmp` a `tmpfs` on Arch?

**Comment by ijustlovemath** [comment]
It is. All files are deleted from /tmp on reboot.

**Comment by thenaterhood** [comment]
Yes it is. Maybe a config option somewhere to remove it on exit would be good too.

**Comment by mezzoatic** [comment]
/tmp may default to being tmpfs in some cases, but there's nothing that says it has to be. I have /tmp mounted as a separate file system, just like /, /var, etc.

**Comment by ijustlovemath** [comment]
Where its physically located on disk or in LVM does not matter. If you
place a file in /tmp and restart, it will be gone. That's decided not at
the user level but at the distro level. I encourage you to try it out.

**Comment by etcusrvar** [comment]
@ijustlovemath That's not true. I use Arch, reboot periodically, and /tmp is not cleared on reboot. This is off-topic, and my setup may be different others', but I was just trying to point out that the assumption that /tmp has to be mounted as tmpfs is incorrect.

**Comment by thenaterhood** [comment]
/tmp should be cleared on a reboot unless you've got something set up so it
isn't.

I guess my reason for this could use a little more clarification. What
happened to me on first run was that my /tmp got filled. I had to add a
bunch of ignores before I could do a save, and needed to remove the folder
from /tmp to get things working. Adding a flag to not keep /tmp after
exiting would have saved me a command the first couple times I ran it.

Not a huge deal either way, just something I felt might be a good addition.

**Comment by etcusrvar** [comment]
"should be cleared on a reboot unless you've got something set up so it isn't" There's nothing that says /tmp **should** be cleared on reboot, and yes, it can be set up so it isn't.

**Comment by ijustlovemath** [comment]
It's the systemd default behavior. Certainly not "should", but "expected".

**Comment by CyberShadow** [comment]
I could add an exit hook that would allow the configuration to clean up the temporary directory on exit.

However, such a solution would not be discoverable, and relies on the user being aware of the problem and the solution only after the problem presents itself. Perhaps it would be better to address the underlying problem directly. To do that, first we should determine what it is.

- `/tmp` becoming full and preventing successive commands from working? Then perhaps `aconfmgr` should warn on exit if free disk space in `/tmp` is low.
- The used space under `/tmp` being an unexpected drain on the system disk space? Then perhaps `aconfmgr` should warn if `/tmp` is not a `tmpfs`, and its temporary directory size exceeds a certain threshold.
- Something else?

**Comment by etcusrvar** [comment]
My personal preference would be to simply document what files/directories are created in /tmp. You may add a config option to use a different base directory from /tmp, but I don't think even this is needed. When I've run into this situation before with other tools (several AUR helpers come to mind), the tool would simply crash when /tmp was full, and I would manually clean up /tmp, put a symlink in /tmp for the offending file/dir to a location with more space, then run the tool again. If aconfmgr filled up my /tmp, I would do the same thing.

**Comment by CyberShadow** [comment]
> My personal preference would be to simply document what files/directories are created in /tmp.

I added a mention to the FILES section of the man page in 68ea74e2e8af9aa0ab2735295d21c05ad7f87d1b.

> You may add a config option to use a different base directory from /tmp, but I don't think even this is needed.

The temporary directory location can be set by setting the `TMPDIR` environment variable, e.g. `TMPDIR=~/.tmp aconfmgr ...`.

**Comment by CyberShadow** [comment]
> Then perhaps aconfmgr should warn on exit if free disk space in /tmp is low

Implemented in c95a65b00536ab80f81359d113a1c9ab7431136d.

If there are no further suggestions, I'll consider this issue resolved.

**Comment by mxmilkb** [comment]
So, as it stands, after my `sudo TMPDIR=/var/aconfmgr/tmp aconfmgr save -c /var/aconfmgr` I'm left with (from `ncdu` ran in /var/aconfmgr);
```
  174.5 MiB [##########] /tmp
  137.4 MiB [#######   ] /files
...
```
To be sure, is my understanding that the /tmp directory is only required for a shorter runtime of `aconfmgr` correct?

**Comment by CyberShadow** [comment]
Yes, if you opt in to that with the `--skip-inspection` switch.

**Comment by mxmilkb** [comment]
Or just by deleting the tmp dir?

**Comment by CyberShadow** [comment]
You can delete it if you don't want to use `--skip-inspection`. Deleting it will not make `aconfmgr` run faster without the switch (and it will fail with the switch).

**Comment by CyberShadow** [comment]
BTW, a configuration size in the order of hundreds of MBs sounds atypical. If some of those files shouldn't be in the configuration, you can ignore them (using `IgnorePath`). If they are modified versions of packaged files, you can use `GetPackageOriginalFile` and related helpers to patch them from your configuration. If they are binaries of built and installed programs, you could package them into a pacman package.
