### ISSUE TITLE
Support `yay` AUR helper

### ISSUE THREAD

**Issue by nunocastromartins** [CyberShadow/aconfmgr#30]
Hi! Any chance of adding `yay` to the list of supported AUR helpers?

I believe that, in terms of the commands used by `aconfmgr`, using `yay` should be very similar, if not equal, to using `pacaur`.

Once again, thank you for your work!

**Comment by CyberShadow** [comment]
Sounds good. Adding support for an AUR helper is fairly simple - here are the changes that were needed to add `aurman`: https://github.com/CyberShadow/aconfmgr/commit/1c0a99441b5e0479d852f1388d81912601415cf1

I'll look into this when I make a time window to work on aconfmgr, but feel free to have a go at it and test it on your side if you're up to it.

**Comment by nunocastromartins** [comment]
I have no way of testing this as I moved from Arch for a while, but thank you @AndreaOrru!
I'll close the issue since it seems to be effectively solved.

As a note for the future (and just in case you didn't know) @AndreaOrru, if you include a description similar to "closes #30" within your PR commit message, GitHub should automatically reference and close this issue, see [GitHub help on closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/).

Once again, thank you! :)

**Comment by AndreaOrru** [comment]
Yup, just forgot about it :)
