### ISSUE TITLE
Sync package DB after updating pacman.conf

### ISSUE THREAD

**Issue by Nils-TUD** [CyberShadow/aconfmgr#33]
I was using aconfmgr to apply my system configuration to another machine and ran into the problem that a package from another repository couldn't be found. This occurs because I also do a ``CopyFile /etc/pacman.conf``, which happens right before in the "Installing priority files" step and adds a new repository. But the package database is not updated afterwards, so that pacman cannot find the package.

I fixed the problem by doing a ``pacman --sync --refresh`` after the installation of the priority files. If you like, I can create a PR.

**Comment by CyberShadow** [comment]
See https://github.com/CyberShadow/aconfmgr/issues/23#issuecomment-356178109 for some discussion on aconfmgr automatically updating package repositories.

I think prompting the user whether they'd like to sync repositories if the pacman configuration was updated (ideally, specifically, the list of repositories) would be a good change.

**Comment by Samisafool** [comment]
Any progress on this? Would love to see this, currently I just rerun aconfmgr after an `-Syu`

**Comment by CyberShadow** [comment]
New features can be added to aconfmgr as soon as either someone contributes a pull request or when I'm able to allocate a time window to work on aconfmgr enhancements (which can be many months apart - I have [a lot of projects](https://github.com/CyberShadow?tab=repositories&type=source) + a job + other hobbies, sorry!)

**Comment by Samisafool** [comment]
> I have [a lot of projects](https://github.com/CyberShadow?tab=repositories&type=source) + a job + other hobbies, sorry!)

Understandable. I would have contributed if I could understand the codebase (It's a big project!)

**Comment by AleksanderBobinski** [comment]
Hi @CyberShadow, would it be possible to bump the AUR package?

**Comment by The-Compiler** [comment]
What's there to bump? It's a -git package, VCS packages always build the newest commit and usually only get updated if e.g. dependencies change.

**Comment by AleksanderBobinski** [comment]
My bad, you are right. I looked at [1] and became confused. Sorry!

[1] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aconfmgr-git#n4
