### ISSUE TITLE
LC_ALL=C: command not found, printf: write error: Broken pipe

### ISSUE THREAD

**Issue by neonn** [CyberShadow/aconfmgr#4]
During a dry run aconfmgr (from the AUR) crashes and produces this error:
```
:::: Done (43 modified files).
::: Reading file attributes...
:::: Reading file types...
/usr/lib/aconfmgr/common.bash: line 928: LC_ALL=C: command not found
/usr/lib/aconfmgr/common.bash: line 928: printf: write error: Broken pipe
:::: Fatal error! Stack trace:
::::: /usr/lib/aconfmgr/common.bash:1 [AconfCompileSystem]
::::: /usr/lib/aconfmgr/common.bash:450 [AconfCompile]
::::: /usr/lib/aconfmgr/save.bash:9 [AconfSave]
::::: /usr/bin/aconfmgr:164 [Main]
::::: /usr/bin/aconfmgr:178 [main]
```

Tried this in both bash and zsh, output is the same. I don't know why LC_ALL is being interpreted as a command, rather than a variable. 

Command used was: `sudo aconfmgr save`

**Comment by CyberShadow** [comment]
Looks like `"$@"` expansion doesn't work with setting environment variables.

This should be fixed now.

By the way, this error would only appear when running `aconfmgr` as root. Some things, such as building AUR packages, actually work better when running without root (it will invoke `sudo` as necessary).
