### ISSUE TITLE
Paranoid mode with priority files does not work

### ISSUE THREAD

**Issue by jfchevrette** [CyberShadow/aconfmgr#40]
If I have the following in my config, and the file in my repo has changes to be applied (different from the one on my system)
```
CopyFile /etc/pacman.conf
```

And I run aconfmgr with the `--paranoid` option, it will ask me if I want to install the file, and then ask about overwriting changed files, to which if I respond with `d` to see a diff, nothing is shown

```
: Applying configuration...
:: Installing priority files...
::: Installing /etc/pacman.conf...
:::: Proceed? [Y/n] y
:::: Done.
::: Done.
:: Configuring packages...
::: Done.
:: Configuring files...
::: Overwriting 1 changed files.
:::: Proceed? [Y/n/d] d
:::: Overwriting the following changed files:
* /etc/pacman.conf
:::: Proceed? [Y/n/d] y
:::: Overwriting /etc/pacman.conf...
::::: Proceed? [Y/n/d] d
::::: Proceed? [Y/n/d] d
::::: Proceed? [Y/n/d] d
::::: Proceed? [Y/n/d] d
```

The problem appears to be that the file is modified after responding `yes` the first time, which then makes diff return no differences. Moreover the fact the file has already been applied makes the second prompt about overwriting the file pointless. 

Non-priority files work fine as expected and a diff is shown.

**Comment by CyberShadow** [comment]
Should be fixed. Thanks for reporting.

**Comment by jfchevrette** [comment]
Thanks @CyberShadow for the quick fix, the priority files are not re-installed again.

However there is no opportunity to diff the files content before applying. I'm not sure if this is a bug or by design, but I feel that like regular files, priority files should be able to be diffed before applying. 

Also note that in the output below even if `/etc/pacman.conf` was changed and changes installed/applied, the last line says `system state unchanged`

```
::: Comparing file data...
::: Changed: /etc/pacman.conf
::: Done (0 only in system, 1 changed, 0 only in config).
:: Examining file properties...
::: Loading data...
:::: Done.
::: Comparing file properties...
:::: Done.
::: Done (0 only in system, 0 changed, 0 only in config).
:: Done.
: Applying configuration...
:: Installing priority files...
::: Installing /etc/pacman.conf...
:::: Proceed? [Y/n] y
:::: Done.
::: Done.
:: Configuring packages...
::: Done.
:: Configuring files...
::: Processing deleted files...
:::: Done.
::: Configuring file properties...
:::: Comparing file properties...
::::: Done.
:::: Done.
::: Done.
:: Done (system state unchanged).
```

**Comment by CyberShadow** [comment]
Well noted on both counts, thanks. Should be fixed.

**Comment by jfchevrette** [comment]
The changes from c620cb92c7990fbf01d6be16d587a1eb175c3074 fixed it. Thanks @CyberShadow !
