### ISSUE TITLE
[Feature Request] Script whitelist. 

### ISSUE THREAD

**Issue by Backfighter** [CyberShadow/aconfmgr#41]
Each created sh-file can be seen as a module.
For example I could have a sh-file that sets up lmms as well as some plugins and other stuff related to music production. 
So this is my music module, there might be modules for development in various languages and so on. 

So now I have a collection of modules but for a workstation I might just want to setup a certain combination of modules to use on this system. 
My computer for work might only use the modules for programming languages used at work. 
While my computer at home uses a different set of modules including the one for music production. 

I'm aware that this can be done with branches. But having a branch for each setup seems like a difficult thing, especially when the number of different used combinations increases. 
And using a module system allows you to easily turn on and off modules when needed. 

So my suggestion would be to allow a whitelist that is stored on each system and determines which scripts are active and considered by aconfmgr (all others will be ignored). The file's path could be an optional parameter to aconfmgr apply and save.

**Comment by CyberShadow** [comment]
The configuration scripts are just bash scripts, so you can do just that with bash constructs.

What I do in my configuration is:

```bash
if [[ "$HOSTNAME" == home.thecybershadow.net ]]
then
	# Directives specific to the home PC
fi
```

For less trivial conditions, the test can be saved to a variable:

```bash
conf_cpu_intel=false
grep -q Intel /proc/cpuinfo && conf_cpu_intel=true

# ...

if $conf_cpu_intel
then
	AddPackage intel-ucode # Microcode update files for Intel CPUs
fi
```

The module system you described can be done as follows:

```bash
if [[ some condition ]]
then
	source "$config_dir"/modules/development.sh
fi
```

then place development rules in `modules/development.sh`.

**Comment by Backfighter** [comment]
Hmm I see. 
So basically I would do something this: 
ˋˋˋ
while read module; do 
  if [ -f "${config_dir}/modules/${module}.sh" ]; then
    source "${config_dir}/modules/${module}.sh"
  fi
done < modules.txt
ˋˋˋ

**Comment by CyberShadow** [comment]
Sure, that looks good, if it works for you.
