### ISSUE TITLE
[Question] Why is /home ignored by default?

### ISSUE THREAD

**Issue by Backfighter** [CyberShadow/aconfmgr#47]
Things like my .zshrc and similar files in /home/username are the configurations files that are the most important to me.
Why are they ignored by default? Can this behaviour be changed?

**Comment by CyberShadow** [comment]
Most users usually use some other method to track their dotfiles, so it makes sense to ignore by default.

The default ignore list is [here](https://github.com/cybershadow/aconfmgr/blob/next/src/common.bash#L36-L54). You can redefine it by simply changing the `ignore_paths` array in your configuration file to the desired value.

A future version of aconfmgr will not have any hard-coded defaults; instead, it will make a guess of what ignore paths make sense considering the installed packages, and place it in the configuration file on the first run.

**Comment by Backfighter** [comment]
Ok I see now. Thank you very much!
