### ISSUE TITLE
Continue instead of failing when refusing to uninstall packages

### ISSUE THREAD

**Issue by BenoitAverty** [CyberShadow/aconfmgr#48]
Hello,

When using `aconfmgr apply`, I would like to have the option to refuse the uninstallation of some packages and still continue the process instead of aborting.

My use case is that I use yay to install aur packages and it installs build dependencies. I'd like to keep those dependencies around to speed up the update process, but aconfmgr always wants to remove then as they are not in my configuration.

I don't want to include these packages in my configuration because I don't use them for anything else, and it would get tedious to maintain this list (add new build dependencies but also remove obsolete ones as I update and remove aur packages)

Thanks in advance.

**Comment by CyberShadow** [comment]
If you can think of a way to programmatically generate a list of such packages, you can add this to your configuration file (by way of `IgnorePackage`).

See also https://github.com/CyberShadow/aconfmgr/issues/16, which is a feature request to have an option to skip the effects of yes/no prompt.

Does yay rebuild said build dependencies if they are not installed? Merely installing a pre-built package shouldn't take much time, but if the AUR helper is rebuilding the dependencies every time, then that would be a problem, and it may be useful to fix it in the AUR helper instead.

**Comment by BenoitAverty** [comment]
They stay in cache, but I clean the cache periodically.
#16 would probably solve my problem, yes. You can probably keep only one of the two issues.

**Comment by CyberShadow** [comment]
Yes, let's continue tracking this in #16.
