### ISSUE TITLE
Running save without any parameters defaults to reading configuration from /etc/xdg/aconfmgr

### ISSUE THREAD

**Issue by v1kn** [CyberShadow/aconfmgr#5]
As per title, despite what the README says, `aconfmgr` does not seem to default to `~/.config/aconfmgr`, but rather  to `/etc/xdg/aconfmgr`. When the folder does not exist (and it doesnt at first), it exits complaining that permission is denied for creating the folder.

**Comment by CyberShadow** [comment]
Aha, looks like I misread the XDG spec.

Should be fixed now.

**Comment by v1kn** [comment]
Great. Should You find some time push the changes to AUR.  
Please and Thank you

**Comment by CyberShadow** [comment]
Simply rebuild the AUR package, it tracks master, so will include the latest changes.

If you use an AUR helper, you may need to coerce it to get the latest commits by deleting its cache or using a switch.

**Comment by v1kn** [comment]
You're right. Updated and tested it, now works as expected
