### ISSUE TITLE
[Feature request] Add option to skip md5sum check when saving configuration

### ISSUE THREAD

**Issue by joanbm** [CyberShadow/aconfmgr#51]
After getting used to aconfmgr, I investigated why it took so long to save the configuration of my system, as I'm tend to save it quite often (when I make changes to the system I prefer to save the configuration and commit the changes ASAP so I have it fresh in my memory).

Most of the time was spent in the "Searching for modified files..." phase, and after some inspection of aconfmgr's source code, I found that it runs `paccheck` with the `--md5sum` option, which means that every time the configuration is saved, aconfmgr hashes the contents of all files of all the packages installed in the system, i.e. through multiple gigabytes of files.

If I remove the `--md5sum` flag from the paccheck call, aconfmgr is still able to detect changes in the package files, as `paccheck` still detects them due to the modification time and/or the size of the files when altering the package files in a reasonable way. This way, the execution time for saving the configuration halves in my system, here is an informal benchmark of it:

```
Cold run (drop caches), no md5sums: 36s
Cold run (drop caches), md5sums: 1m 45s
Warm run, no md5sums: 29s
Warm run, md5sums: 50s

Root partition is 18GB (most of it packages), in an SSD, and enough RAM to hold it entirely
````

I suppose running with the `--md5sum` option is intended (and necessary) to make 100% sure that the package has not been modified since it was installed. However, I think running a hash check every time one wants to save the configuration is overkill, and noticeably increments the execution time. I have been running my system for 3 months without the flag and after re-enabling it, no change was detected. Similarly, tools like rsync even default to checking for modification time and size and only do checksums if explicitly specified.

To start with, what do you think about adding a flag (e.g. `--no-md5sum`) that avoids checking the checksums of the packages when saving the configuration? I'll look into sending a PR if I can find some time, so I'm mostly interested in feedback.

**Comment by CyberShadow** [comment]
Thank you for the detailed issue. I've been meaning to add `--quick` to do just this. If you'd like to implement it and submit a pull request, please do :)
