### ISSUE TITLE
Unknown paccheck output line: unknown option: 'SyncFirst'

### ISSUE THREAD

**Issue by dniku** [CyberShadow/aconfmgr#59]
During the initial `aconfmgr save`, the following line is printed to the console:

```
:::: Unknown paccheck output line: warning:\ config\ /etc/pacman.conf\ line\ 20:\ unknown\ option\ \'SyncFirst\'
```

Not sure whether this is an issue or not.

**Comment by CyberShadow** [comment]
The `SyncFirst` option has been removed from pacman.conf. Looks like paccheck is using pacman's libraries to parse it. You probably want to update your file to use the current syntax as per pacman.conf(5).

The warning should have no effect on aconfmgr.

**Comment by dniku** [comment]
Thank you for the clarification. I have [reported](https://gitlab.manjaro.org/packages/core/pacman/issues/3) the issue to Manjaro bug tracker.

Would it be possible to provide a more useful error message under similar circumstances? Currently, `Unknown output line` does not clarify whether this is a problem for `aconfmgr` or not.

**Comment by CyberShadow** [comment]
> Would it be possible to provide a more useful error message under similar circumstances?

aconfmgr cannot possibly predict all error messages and failure modes of other software it invokes. The only actionable option is to present the message as it is printed by paccheck, i.e. without ":::: Unknown paccheck output line: " and string escaping.

**Comment by dniku** [comment]
Thank you. In any case, the issue is now fixed by Manjaro, and this problem should not arise again.
