### ISSUE TITLE
Unknown paccheck output line: mtree data not available

### ISSUE THREAD

**Issue by dniku** [CyberShadow/aconfmgr#60]
During the initial `aconfmgr save`, the following lines are printed to the console:

```
:::: Unknown paccheck output line: warning:\ lsb-release:\ mtree\ data\ not\ available\ \(No\ such\ file\ or\ directory\)
:::: Unknown paccheck output line: warning:\ lsb-release:\ mtree\ data\ not\ available\ \(No\ such\ file\ or\ directory\)
:::: Unknown paccheck output line: warning:\ manjaro-alsa:\ mtree\ data\ not\ available\ \(No\ such\ file\ or\ directory\)
:::: Unknown paccheck output line: warning:\ manjaro-alsa:\ mtree\ data\ not\ available\ \(No\ such\ file\ or\ directory\)
:::: Unknown paccheck output line: warning:\ manjaro-pulse:\ mtree\ data\ not\ available\ \(No\ such\ file\ or\ directory\)
:::: Unknown paccheck output line: warning:\ manjaro-pulse:\ mtree\ data\ not\ available\ \(No\ such\ file\ or\ directory\)
```

Not sure whether these are issues or not.

**Comment by CyberShadow** [comment]
Without mtree data, aconfmgr will not be able to verify that the files in these packages have been modified or not. You will also be unable to customize files owned by these packages using aconfmgr. 

You will need to contact your distribution's (apparently not Arch Linux) packagers for these packages to inquire why they do not contain an `.MTREE` file.

**Comment by dniku** [comment]
I am indeed using Manjaro, not vanilla Arch. Thank you for the clarification.

**Comment by dniku** [comment]
Perhaps it would be possible to provide more informative error messages though? The current message only says that `aconfmgr` cannot interpret something, and does not say whether this is a bad thing or something to be ignored.

**Comment by digitalsignalperson** [comment]
I just fired up a VM with Manjaro 19.0.1 and cloned aconfmgr. Do not see any errors on `aconfmgr save`

**Comment by dniku** [comment]
The errors aren't there anymore. I guess Manjaro have fixed them.
