### ISSUE TITLE
Sort 99-unsorted.sh by repo?

### ISSUE THREAD

**Issue by mxmilkiib** [CyberShadow/aconfmgr#62]
By default the packages are in a big long alphabetical list. I think it would be easier to parse and rewrite if the list was separated into core/ extra/ community/ aur/ etc.

**Comment by CyberShadow** [comment]
I'm not sure that distinction is useful to many users. Though for some packages it is easy to predict which repository they would be located in, for others it is somewhat arbitrary.

Note that foreign packages are already listed as a separate category from native ones.

I think this would be useful in conjunction with an option to pin packages to their repositories, in which case the packages would be specified as e.g. `core/linux`. Then, lexicographical sorting would take care of grouping the packages by repository. (See also #42 for a discussion on pinning packages to a version.)

**Comment by CyberShadow** [comment]
Closing, but thanks anyway for filing the suggestion.
