### ISSUE TITLE
grep dependency missing

### ISSUE THREAD

**Issue by OJFord** [CyberShadow/aconfmgr#67]
`grep` is missing from PKGCONFIG, and also isn't installed at runtime like others. (Or perhaps it is, but it's used first.)

```
::: Querying package list...
src/common.bash: line 172: grep: command not found
:::: Fatal error! Stack trace:
::::: src/common.bash:172 [AconfCompileSystem]
::::: src/common.bash:783 [AconfCompile]
::::: src/save.bash:9 [AconfSave]
::::: src/main.bash:160 [Main]
::::: src/main.bash:177 [source]
::::: ./aconfmgr:26 [main]
```

**Comment by CyberShadow** [comment]
What's PKGCONFIG? I am assuming you actually mean PKGBUILD.

Kindly read https://wiki.archlinux.org/index.php/Arch_User_Repository#Prerequisites (and other occurrences of `base-devel` on that page).

**Comment by CyberShadow** [comment]
Though, it should still be specified as a runtime dependency.

**Comment by CyberShadow** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=aconfmgr-git&id=ea7c648f8023d074213692e2f0e59ae6523d8afc

Thanks!
