### ISSUE TITLE
Add support for aurutils

### ISSUE THREAD

**Issue by Strykar** [CyberShadow/aconfmgr#68]
Please add `aur`/[aurutils](https://github.com/AladW/aurutils) support as yay and a bunch are already supported.

**Comment by CyberShadow** [comment]
aurutils is what I personally use these days, but I don't really imagine how aconfmgr integration would look like, considering that aurutils builds a pacman repo and packages are then installed using pacman as usual. Could you describe in more detail what you find missing in aconfmgr?

**Comment by CyberShadow** [comment]
No response and it is unclear what needs to be done, closing.

**Comment by Strykar** [comment]
@CyberShadow You're right, aurutils support needs no change.
