### ISSUE TITLE
[feature request] Add an optional configuration file, to store arguments that can be specified on the command line

### ISSUE THREAD

**Issue by v1kn** [CyberShadow/aconfmgr#7]
As of now this may be low priority, due to limited amount of CLI options.  

However, it would be beneficial to have a `aconfmgr.conf` or `config` file ~~inside the configuration directory~~ (most likely outside of it, if it's a custom path), that would hold custom CLI arguments, like `aur-helper` of choice, `paranoid` or `verbose` state, or custom configuration path

**Comment by CyberShadow** [comment]
The configuration scripts have access to aconfmgr's variables, so you can just set them from your configuration. The respective variables are `aur_helper`, `prompt_mode` (with values `never` / `normal` / `paranoid`), and `verbose` (0/1).

**Comment by v1kn** [comment]
ah, that is handy. fourth value i tested out now and was accepted by sourcing, was `color=always`.  
Ok good to know
