### ISSUE TITLE
Ignore 'modification time mismatch' from paccheck?

### ISSUE THREAD

**Issue by Anarky** [CyberShadow/aconfmgr#75]
Hello, I was wondering if it was useful to process a file as "modified" when its only modification is its date.
For example, I removed the modification I made in `/etc/exports`, but it will still be copied for `nfs-utils`, even if its md5 now matches.
Same for `linux`, I ignored the `modules.alias/dep/symbols` because of the nVidia and VirtualBox modules, but `modules.builtin/devname/softdep` are reported as modified only for their date.

I can do a pull request for this change if it can be ignored; maybe a `--skip-modtime` option to not break the new `--skip-checksums`?

**Comment by CyberShadow** [comment]
The canonical way to handle this situation is to run `aconfmgr apply`, and allow it to restore the original file, including its modification time.

Would that work for you?

**Comment by Anarky** [comment]
I don't see the point to backup those files, especially since it means to add a CopyFile somewhere.

My system was installed five years ago and it's the first time that I try to use aconfmgr (btw thanks a lot for this tool!), so I have a lot of files to review, and I see those kind of warnings as "useless".

**Comment by CyberShadow** [comment]
> I don't see the point to backup those files, especially since it means to add a CopyFile somewhere.

I think that's a misunderstanding.

A file which is owned by some package, is not listed in your configuration, and has been modified (compared to the packaged version) will be restored to the original version by `aconfmgr apply`.

> My system was installed five years ago and it's the first time that I try to use aconfmgr (btw thanks a lot for this tool!), so I have a lot of files to review, and I see those kind of warnings as "useless".

The appropriate action is to delete the `CopyFile` line added by `aconfmgr save`. When you finish reviewing the generated configuration, run `aconfmgr apply` to make it restore the original files.

**Comment by Anarky** [comment]
Thanks, I see the procedure now.
But it means that every time I run `aconfmgr save`, I will delete those `CopyFile` because I know their modification are only their date, delete them from the `files` folder... At one point I'm afraid to disregard a legit modification.

Would you accept such an option if I create a PR for it?

**Comment by CyberShadow** [comment]
> But it means that every time I run `aconfmgr save`, I will delete those `CopyFile` because I know their modification are only their date,

No, because after you run `aconfmgr apply`, aconfmgr will restore the files to the original time stamp, and they will no longer appear in your configuration after `aconfmgr save`.

> At one point I'm afraid to disregard a legit modification.

`aconfmgr apply` will let you review every modification it does to the system before it performs it. With `--paranoid`, this becomes very fine-grained.

> Would you accept such an option if I create a PR for it?

According to my understanding of the situation, it is not necessary, as the problem is better solved using the existing functionality. But, it's possible I'm wrong or I have misunderstood something, so please correct me if that is the case.

**Comment by Anarky** [comment]
> > But it means that every time I run `aconfmgr save`, I will delete those `CopyFile` because I know their modification are only their date,
> 
> No, because after you run `aconfmgr apply`, aconfmgr will restore the files to the original time stamp, and they will no longer appear in your configuration after `aconfmgr save`.

I might be missing something, I can't see how it restores the file to the **package** original timestamp.
For example:
```
$ paccheck --file-properties --backup nfs-utils
nfs-utils: '/etc/exports' modification time mismatch (expected 2020-02-15 11:04:25)
```
It added `CopyFile /etc/exports` and copied it inside `files`, with a timestamp from when I executed `save`.

I hadn't try `apply` yet, but by reading the `CopyFile(To)` functions, the `exports` file will be overwritten with another timestamp, which is still different than the package's file timestamp.
So the next time I use `save`, it will repeat the same cycle.

**Comment by CyberShadow** [comment]
> It added `CopyFile /etc/exports` and copied it inside `files`, with a timestamp from when I executed `save`.

If you delete the `CopyFile` line, and run `aconfmgr apply`, it will restore it to the original package version. That's what I meant when I said "not listed in your configuration".

**Comment by Anarky** [comment]
Thanks for your time, I finally tried the `apply` option, it did restored the file. Closing this "issue"!
