### ISSUE TITLE
"Lost files" a bit confusing

### ISSUE THREAD

**Issue by alecmev** [CyberShadow/aconfmgr#77]
To me, a new user, "lost files" sounds like a quirky synonym to "missing files", i.e. files which are supposed to be there, but aren't. "Lost" carries this "uh-oh, not good" connotation. It took me some time to figure out that it's actually the inverse. I've looked up the history of the terminology, and looks like these files were previously called ["untracked"](https://github.com/CyberShadow/aconfmgr/commit/2ec35f5191b85dac09f045517ede2fd64395e2ab), which is much more intuitive. Why the change?

**Comment by CyberShadow** [comment]
> Why the change?

In order to align aconfmgr with terminology that's already established in Arch Linux:
https://github.com/graysky2/lostfiles

**Comment by alecmev** [comment]
But `lostfiles` doesn't actually refer to these files as "lost", I think it's just a poetic name for the utility. In the readme and the docs it calls them ...

["files not owned and not created by any Arch Linux package"](https://github.com/graysky2/lostfiles/blame/de6ef2d0b6712e21732cea94bd2c1683e2d02d9c/README.md#L2)
["orphaned files not owned by any packages"](https://github.com/graysky2/lostfiles/blob/de6ef2d0b6712e21732cea94bd2c1683e2d02d9c/doc/lostfiles.1#L4)
["[files] not owned by a package"](https://github.com/graysky2/lostfiles/blob/de6ef2d0b6712e21732cea94bd2c1683e2d02d9c/doc/lostfiles.1#L9)
["non-native files"](https://github.com/graysky2/lostfiles/blob/de6ef2d0b6712e21732cea94bd2c1683e2d02d9c/doc/lostfiles.1#L9)

... never "lost".

**Comment by CyberShadow** [comment]
Fair point.

I don't think "untracked" is optimal, because within the context of aconfmgr, these files *are* tracked within the configuration (either as added files or as ignore rules).

Probably we should pick one of "orphan" / "orphaned" / ["ghost"](https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Tracking_unowned_files_created_by_packages).

**Comment by alecmev** [comment]
> I don't think "untracked" is optimal

I agree.

> "orphan" / "orphaned" / "ghost"

What about configuration files? They aren't orphans or ghosts.

[This article](https://raphaelhertzog.com/2011/02/28/debian-cleanup-tip-5-identify-cruft-that-can-be-removed-from-your-debian-system/) uses "non-packaged".
[`cruft-ng`](https://github.com/a-detiste/cruft-ng/blob/master/cruft-ng.8) calls them "unexplained".

**Comment by CyberShadow** [comment]
> What about configuration files? They aren't orphans or ghosts.

They are orphans in the sense that they are not owned by any package (even if said packages include programs which use them, this relationship is not formally declared anywhere).

**Comment by alecmev** [comment]
Doesn't being an "orphan" imply being abandoned by something? Orphaned process' parent is terminated. Orphaned inode isn't linked to anymore. I think unused packages are called "orphans" in Arch because they're often abandoned optional dependencies of something that isn't installed anymore.

What about "unmanaged"? Since it's the opposite of `tmp/managed-files`.

**Comment by CyberShadow** [comment]
> Doesn't being an "orphan" imply being abandoned by something?

"Orphaned", yes, but "orphan", I don't know. I wouldn't think further than "orphan" being something with no parents. E.g., objects with start out as orphans and then become adopted doesn't seem that otherworldly to me.

> What about "unmanaged"?

I think it has the same problem as "untracked". (But, so does "managed".)

>  [`cruft-ng`](https://github.com/a-detiste/cruft-ng/blob/master/cruft-ng.8) calls them "unexplained".

I think that's not the same meaning (not owned by a package, and also not covered by any cruft-ng rule.)

Another possibility is "owned" / "unowned", but "owner" is already a property of files with a different meaning (as in `chown`).

**Comment by alecmev** [comment]
[Asked /r/archlinux's opinion](https://www.reddit.com/r/archlinux/comments/gcg03s/the_most_intuitive_term_for_all_files_on_the/), thoughts?

**Comment by CyberShadow** [comment]
> [Asked /r/archlinux's opinion](https://www.reddit.com/r/archlinux/comments/gcg03s/the_most_intuitive_term_for_all_files_on_the/)

Nice!

> thoughts?

I really like "stray"!

I also see there's a poll linked, but I don't see a way to see the results without voting in the poll, which I don't want to do as it would skew the results.

**Comment by alecmev** [comment]
> I also see there's a poll linked, but I don't see a way to see the results without voting in the poll, which I don't want to do as it would skew the results.

No problem:

![image](https://user-images.githubusercontent.com/2584727/80925249-1115d900-8d86-11ea-8980-abd9a3319ca8.png)

**Comment by CyberShadow** [comment]
OK!

I can think of the following metrics for ranking candidates:

- Ideally, has an obvious counterpart (antonym), to also replace the use of "managed"
- Ideally, not easily confusable with "(not) managed by aconfmgr"
- Ideally, not easily confusable with an existing relevant property (such as UNIX file owner)
- Ideally, represents the idea well enough to avoid confusion such as with "lost"
- Ideally, short and memorable, so that it can be combined with similar terms to describe files without making the sentence awkward, or make the progress output boring or tedious to follow

I would thus rank them as follows:

1. owned / stray (like e.g. a cat)
2. owned / unowned
3. packaged / non-packaged
4. managed / unmanaged
5. ? / ghost

Unowned is pretty far down the list in the poll, though...

**Comment by alecmev** [comment]
Pacman-managed/pacman-unmanaged, perhaps? Not short, but not that awkward.

**Comment by CyberShadow** [comment]
These are now in `next`:

- eeac4db
- b15b7cd

**Comment by alecmev** [comment]
Excellent, thank you!

**Comment by CyberShadow** [comment]
And now in `master`. :)
