### ISSUE TITLE
[QUESTION] Workflow for ignoring files

### ISSUE THREAD

**Issue by setzer22** [CyberShadow/aconfmgr#78]
Hi! I'm asking the question here because I didn't see any forum or better place to ask for support sorry about that.

As a newcomer, the behaviour of aconfmgr is a bit confusing to me. Imagine the following situation:

- I install a new package, say `docker`, using `pacman -S docker`.
- This package creates new folders, like `/etc/docker`
- I run `aconfmgr save`, and files under `/etc/docker/` end up as CopyFile directives in my `99-unsorted.sh`

Now, here's the part I don't understand: Let's say I decide I do not want aconfmgr to track the folders inside `/etc/docker`. What I'm currently doing is:

- Remove the `CopyFile` calls from `99-unsorted.sh`. 
- Add a `IgnorePath '/etc/docker/'` call in my `05-ignores.sh`. 

During this process, I also keep and sort the relevant commands such as `AddPackage docker` that were generated for me in `99-unsorted.sh`.

Now, the problem comes when I run `aconfmgr apply` after all this procedure. The first thing aconfmgr tries to do is delete all files under `/etc/docker`! I don't understant this behaviour: I've purposefully ignored these folders, why is aconfmgr trying to manage them?

I think there may be something wrong with my workflow, but I haven't been able to find more info on this after reading the README and Wiki pages.

Thanks!

**Comment by CyberShadow** [comment]
>     * `IgnorePath '/etc/docker/'`

The correct syntax would be `IgnorePath '/etc/docker/*'`.

(`IgnorePath '/etc/docker'` will also work, but only in certain circumstances, and is not recommended.)

`IgnorePath '/etc/docker/'` will not work, as you have observed.

**Comment by setzer22** [comment]
Thanks for the tip, my bad! However, I think I'm still missing something. After adding the following line to `05-ignores.sh`: `IgnorePath '/etc/docker/*'`, I re-ran `aconfmgr save` and `99-unsorted.sh` still contains lines like: `RemoveFile /etc/docker/key.json`.

I've checked my `files` folder inside the configuration directory the `key.json` file is there (probably got copied when I run the first save). Do I need to delete it? I've been assuming aconfmgr takes care of that for me and I don't need to touch the `files` folder at all, so please correct me if I'm wrong!

**Comment by CyberShadow** [comment]
> I re-ran `aconfmgr save` and `99-unsorted.sh` still contains lines like: `RemoveFile /etc/docker/key.json`.

The only reason `aconfmgr save` would emit `RemoveFile` is if there is a line adding a file somewhere in your configuration. You will need to find it and remove it.

> I've been assuming aconfmgr takes care of that for me and I don't need to touch the `files` folder at all, so please correct me if I'm wrong!

`aconfmgr` allows unused files in the `files` directory (because e.g. they are used conditionally). Run `aconfmgr lint` to detect them. However, the presence or absence of files in the `files` directory does not affect the generated system configuration (a file which is absent when it is referenced causes an error, and a file which is present when it is not referenced is ignored).

**Comment by setzer22** [comment]
I see, the problem in this case was that I forgot to remove the `CopyFile` calls in 99-unsorted.conf that were generated by my first call to `aconfmgr save`. Thanks again!

I'm closing this because my question is solved. Also, is there a better place to ask questions about aconfmgr?
