### ISSUE TITLE
/usr/lib/modules detected as new files, despite owned by linux package

### ISSUE THREAD

**Issue by OJFord** [CyberShadow/aconfmgr#79]
In my configuration I have:
```
AddPackage linux
```

and no mention of `/usr/lib/modules` (or anything deeper).

When I run `aconfmgr save`:
```
::: Only in system: /usr/lib/modules
::: Only in system: /usr/lib/modules/5.6.8-arch1-1
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.alias
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.alias.bin
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.builtin.alias.bin
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.builtin.bin
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.dep
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.dep.bin
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.devname
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.softdep
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.symbols
::: Only in system: /usr/lib/modules/5.6.8-arch1-1/modules.symbols.bin
```

Which `pacman -Qo` reports are owned by `linux`.

I'm not sure why they're not being detected as covered by the `AddPackage linux`?

**Comment by CyberShadow** [comment]
These files, despite being owned by a package, may be modified from the original packaged version. I think a common cause is installing out-of-tree kernel modules (nvidia?).

By itself, the line `AddPackage linux` in your configuration states that this package is installed, and all files owned by this package are untouched and identical by the package version. This is why `aconfmgr save` will emit additional `CopyFile` lines to represent changes in these files compared to the original package version.

As these files are automatically generated/updated using other configuration on your system, [ignoring them](https://github.com/CyberShadow/aconfmgr#ignoring-files) is an appropriate way to handle them in aconfmgr.

**Comment by OJFord** [comment]
I neglected to include the summary at the bottom of the output, but should they not show as 'modified files' in that case?

(I had 1 modified file, which was something else, and assumed these were included in the 'new files' count.)

**Comment by CyberShadow** [comment]
> I neglected to include the summary at the bottom of the output, but should they not show as 'modified files' in that case?

Yes, during the stage where aconfmgr collects information about the current system state, but not during the stage where the system and configuration states are compared, which is where your log excerpt is from.

**Comment by jmacmahon** [comment]
These files are not modified on my system, yet are included in `99-unsorted.sh`. Adding an `IgnorePath '/usr/lib/modules'` command does not work, and they are still included.

**Comment by CyberShadow** [comment]
> These files are not modified on my system, yet are included in `99-unsorted.sh`.

A modified file that's owned by a package is not the only reason why it would be added to your configuration. Check the section where it's added.

> Adding an `IgnorePath '/usr/lib/modules'` command does not work, and they are still included.

Nor should it, as that's not the correct way to use `IgnorePath`. Kindly recheck the documentation.

**Comment by jmacmahon** [comment]
As I understood it, this tool adds the following as `CopyFile` rules (regardless of packages and symlinks):
- Files not owned by any package
- Files owned by a package which have been modified.

If there are other rules for what files are added, I cannot find them in the documentation. They are added in the section marked `New / changed files`, which is at least not an accurate description.

Regarding your second point, the documentation states

> `IgnorePath PATTERN` - Adds the specified pattern to the list of ignored paths.

As I understand this, it means that what I wrote is correct. If that is not the case can you clarify, and I can submit a patch to the documentation? If you are trying to tell me that only _files_ may be specified as `PATTERN`, and not directories, that is certainly not clear.

**Comment by CyberShadow** [comment]
You can look at the output of `paccheck --files --file-properties --backup --noupgrade --md5sum` for the reason that aconfmgr considers a package-owned file modified.

> As I understand this, it means that what I wrote is correct. If that is not the case can you clarify,

The pattern `'/usr/lib/modules'` matches exactly one string: `'/usr/lib/modules'`. There are several examples in the documentation for the proper way to use `IgnorePath`, please have a look there.
