### ISSUE TITLE
Problem with read

### ISSUE THREAD

**Issue by thenaterhood** [CyberShadow/aconfmgr#8]
I've traced this back to I believe line 793 of common.bash. I have two different issues, one with zsh and one with bash. This is what happens when I reach that point in the script, without hitting any keys; I'm running `aconfmgr apply -c .` and leaving it alone.

In bash, I get:

```
: Applying configuration...
:: Installing priority files...
::: Installing /etc/pacman.conf...
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: Proceed? [Y/n] 
:::: User abort
```

And in zsh I get:
```
: Applying configuration...
:: Installing priority files...
::: Installing /etc/pacman.conf...
:::: Proceed? [Y/n] ::::: Fatal error! Stack trace:
:::::: /usr/lib/aconfmgr/common.bash:1 [Confirm]
:::::: /usr/lib/aconfmgr/apply.bash:110 [AconfApply]
:::::: /usr/bin/aconfmgr:167 [Main]
:::::: /usr/bin/aconfmgr:178 [main]
```

From what I've been able to tell, other actions have worked fine, it's just copying over files that's an issue (removing files, and adding and removing packages has been fine).

**Comment by CyberShadow** [comment]
Odd. The choice of shell should not matter, can you reproduce this consistently?

Perhaps try a different terminal emulator.

**Comment by thenaterhood** [comment]
Local console has the same issue.

**Comment by CyberShadow** [comment]
Sorry, upon another look the problem became obvious. (The `read` is inside a `while` loop with its stdin redirected.)

Should be fixed now.
