### ISSUE TITLE
IgnorePath brace expansion

### ISSUE THREAD

**Issue by OJFord** [CyberShadow/aconfmgr#80]
It'd be nice to be able to use brace expansion in `IgnorePath`s in particular.

For example, I'd like to write after `AddPackage firefox`:
```
IgnorePath '/usr/share/fonts/{TTF,noto}/fonts.{dir,scale}'
```

which otherwise either takes four lines, or loses specificity with globbing.

**Comment by CyberShadow** [comment]
You can already do this, just don't quote the part in `{` / `}`.

This is a bash feature.

For the parts of the string that are quoted, aconfmgr is limited to the syntax provided by the `find` utility, which on Arch Linux is GNU find, which uses the system `fnmatch` function (see `man 3 fnmatch`).

**Comment by OJFord** [comment]
Oh. OK, thank you.

It might be worth adding that as a tip to the readme, where it says:
> Make sure to quote the pattern argument to prevent globbing at configuration parse time.

I assumed the same advice would apply to brace expansion if it were supported, so when I tried it (making sure to quote the pattern argument) and it didn't work I just assumed it wasn't evaluated by bash.
