### ISSUE TITLE
Filter feature for CopyFile?

### ISSUE THREAD

**Issue by The-Compiler** [CyberShadow/aconfmgr#84]
I'd like to track NetworkManager's `.nmconnection` files in `/etc/NetworkManager/system-connections` with aconfmgr. However, it looks like it adds a `timestamp` value when connecting:

```diff
--- i/files/etc/NetworkManager/system-connections/Nokia 8 Network.nmconnection  
+++ w/files/etc/NetworkManager/system-connections/Nokia 8 Network.nmconnection  
@@ -4,6 +4,7 @@ uuid=29a0af8a-3247-40d4-b2ef-414d009b840c
 type=bluetooth
 autoconnect=false
 permissions=
+timestamp=1599846521
```

Thus, the file changes with every connection. It *does* seem to work fine without that `timestamp` line though. Thus, I'd like to somehow be able to filter it out, i.e. by piping it to `sed -i '/timestamp=/d' filename` or similar. That would then be applied every time aconfmgr copies it to its local files, so that it would not detect any modifications even if that timestamp line was added/changed.

Is something like that possible at the moment? If not, would it sound like a good idea? I can't commit to submitting a PR at the moment, as there's quite a lot on my plate currently.

**Comment by CyberShadow** [comment]
How does a639a4912072128175dcc0a72b3db688967fe22e look?

**Comment by The-Compiler** [comment]
That looks great! :heart: I can't test it right now, as I can't figure out how to get the timestamp line back... no idea when NetworkManager writes it exactly.

I wonder, should the first argument to `AddFileContentFilter` really be a regex rather than a pattern like with `IgnorePath`? It seems inconsistent and a bit awkward to use (since filenames often have periods you'd need to escape). Personally I'd be okay with only supporting patterns.

**Comment by CyberShadow** [comment]
Yes, good points. Changed to a glob pattern: 0f7cd7a6595ea4ac42da3116d33fce333b24866e

**Comment by The-Compiler** [comment]
I finally got around to testing the `next` branch and it works beautifully - thanks again!

**Comment by CyberShadow** [comment]
Thanks for the feedback. This is now in master.
