### ISSUE TITLE
CreateFile but then ignore change?

### ISSUE THREAD

**Issue by OJFord** [CyberShadow/aconfmgr#85]
I create my pacman mirrorlist dynamically, since I don't really have any reason to set some specifically in my aconfmgr files:

```sh
curl --silent 'https://www.archlinux.org/mirrorlist/?country=GB&protocol=https&use_mirror_status=on' \
    | sed -e 's/^#Server/Server/g' -e '/^#/d' \
    | rankmirrors -n 5 - \
    | sort \
    > "$(CreateFile '/etc/pacman.d/mirrorlist')"
```

The problem then is that when it changes, `aconfmgr save` wants to `CopyFile` the new version. If I `IgnorePath` afterwards, it wants to `RemoveFile`.

(NB the `sort` is there just to reduce the frequency with which this happens, of course it destroys the ranking within the chosen `-n 5`, but that's fine for me.)

Is there any way to create but then ignore subsequent changes?

**Comment by CyberShadow** [comment]
It sounds like your intent is to make the configuration depend on an external condition, namely whether the mirror list has been generated on this system yet. So, do just that:

```bash
if [[ -f /etc/pacman.d/mirrorlist ]]
then
    curl ... > "$(CreateFile '/etc/pacman.d/mirrorlist')"
else
    IgnorePath '/etc/pacman.d/mirrorlist'
fi
```

**Comment by CyberShadow** [comment]
I am assuming that this question is resolved.

**Comment by OJFord** [comment]
Sorry, yes, I see now, thanks!
