### ISSUE TITLE
[Feature Request] Change backup location

### ISSUE THREAD

**Issue by smac89** [CyberShadow/aconfmgr#89]
Is there a way to use a different backup location which is not in the same folder as the config scripts? 

If not, can you include such an option? I was hoping to have a way to backup to an external drive, but it looks like I would have to copy my scripts to the backup drive.

**Comment by CyberShadow** [comment]
Have you tried making `files` be a symlink to your desired location?

Note that aconfmgr wasn't designed to be a backup tool, so your use case may be outside of the tool's intended scope.

**Comment by smac89** [comment]
> Have you tried making `files` be a symlink to your desired location?
> 
> **Note that aconfmgr wasn't designed to be a backup tool, so your use case may be outside of the tool's intended scope.**

Thank you for the clarification. My files directory is about 8.4GB right now.

I should have paid more attention to the word "configuration" in that README. So what I should be saving are my configurations so things like:

- `/etc/pacman.conf`
- `/etc/unbound/unbound.conf`
- `/etc/sddm.conf`
- `/usr/lib/udev/rules.d/00-custom.rules`
- etc?

Also should I delete the `files` directory each time I delete the `99-unsorted.sh` file? I just looked in that folder and it seems `aconfmgr` does not remove files which I have already deleted from my system since I last ran `aconfmgr save`

**Comment by CyberShadow** [comment]
> etc?

That's the intended use case, yes.

> Also should I delete the `files` directory each time I delete the `99-unsorted.sh` file?

No, unless your configuration is completely devoid of `CopyFile` calls. `CopyFile` copies files from the `files` directory.

> I just looked in that folder and it seems `aconfmgr` does not remove files which I have already deleted from my system since I last ran `aconfmgr save`

It doesn't know if they are used or not, because their use may be conditional. The `check` action identifies files that were not used during sourcing the configuration.
