### ISSUE TITLE
GetPackageOriginalFile doesn't work when the system is set to a non-english language

### ISSUE THREAD

**Issue by thwischm** [CyberShadow/aconfmgr#91]
Hello,

I'm switching my system over to use aconfmgr and it's been working really well so far, with one exception: When I tried to use the GetPackageOriginalFile helper, running `aconfmgr apply` failed with this stack trace:

```
:::: Fatal error! Stack trace:
::::: /usr/lib/aconfmgr/common.bash:1295 [AconfNeedPackageFile]
::::: /usr/lib/aconfmgr/common.bash:1473 [AconfGetPackageOriginalFile]
::::: /usr/lib/aconfmgr/helpers.bash:185 [GetPackageOriginalFile]
::::: /home/salmiak/.config/aconfmgr/30-pulseaudio.sh:6 [source]
::::: /usr/lib/aconfmgr/common.bash:124 [AconfCompileOutput]
::::: /usr/lib/aconfmgr/common.bash:870 [AconfCompile]
::::: /usr/lib/aconfmgr/apply.bash:168 [AconfApply]
::::: /usr/lib/aconfmgr/main.bash:169 [Main]
::::: /usr/lib/aconfmgr/main.bash:183 [source]
::::: /usr/bin/aconfmgr:26 [main]
```

I looked at the implementation of AconfNeedPackageFile and it looks like it's parsing the output of pacman and expects it to be in English. And indeed when I run `LANG=en_US.UTF-8 aconfmgr apply` everything works as expected.

aconfmgr should probably make sure that it calls pacman with the language set to English, regardless of the system locale.

**Comment by CyberShadow** [comment]
Should be fixed as of bd94197ff28ff02db6720bcfc42aa95b76d82a74, thanks!
