### ISSUE TITLE
Crashs everytime

### ISSUE THREAD

**Issue by mgabs** [CyberShadow/aconfmgr#92]
Hi,

Each time I ran aconfmgr i get a crash with the following 
```
:::: Warning: copying large file /boot/initramfs-linux-lts-fallback.img (25911184 bytes). Add IgnorePath /boot/initramfs-linux-lts-fallback.img to configuration to ignore.
:::: Warning: copying large file /boot/initramfs-linux-fallback.img (26886172 bytes). Add IgnorePath /boot/initramfs-linux-fallback.img to configuration to ignore.
cat: /var/log/journal/6597155ae1754b9ead190796947d21a8/system@0005b8ff6500c8f2-a28e0da1c53cbeb0.journal~: No such file or directory
:::: Fatal error! Stack trace:
::::: /usr/lib/aconfmgr/common.bash:602 [AconfCompileSystem]
::::: /usr/lib/aconfmgr/common.bash:883 [AconfCompile]
::::: /usr/lib/aconfmgr/save.bash:9 [AconfSave]
::::: /usr/lib/aconfmgr/main.bash:185 [Main]
::::: /usr/lib/aconfmgr/main.bash:205 [source]
::::: /usr/bin/aconfmgr:26 [main]
```
I have no config, this the absolute first run!

**Comment by CyberShadow** [comment]
Looks like a race condition - systemd-journal created and then renamed/deleted that file as aconfmgr was scanning the filesystem. I don't know why you would get that error every time, but you can avoid it by creating a minimal configuration consisting of only ignore rules before the first run.

```shell
$ mkdir config
$ echo "IgnorePath '/var/log/journal/*'" > config/01-ignores.sh
```

**Comment by jcguu95** [comment]
I got similar issues too. Having done the patch mentioned above

```
cat ./config/aconfmgr/01-ignores.sh

IgnorePath 'var/lib/*'
IgnorePath 'usr/share/mime/*'
```

I still get fatal errors:

```
[..]
Enumerating owned files...
Done.
Searching for stary files...
[sudo] password for ome:
find: File system loop deteced: '/home' is part of the same file system loop as '/'.
Fatal error! Stack trace:
/usr/lib/aconfmgr/common.bash:330 [AconfCompileSystem]
/usr/lib/aconfmgr/common.bash:883 [AconfCompile]
/usr/lib/aconfmgr/save.bash:9 [AconfSave]
/usr/lib/aconfmgr/main.bash:185 [Main]
/usr/lib/aconfmgr/main.bash:205 [Source]
/usr/bin/aconfmgr:26 [main]
Fatal error! Stack trace:
/usr/lib/aconfmgr/common.bash:332 [AconfCompileSystem]
/usr/lib/aconfmgr/common.bash:883 [AconfCompile]
/usr/lib/aconfmgr/save.bash:9 [AconfSave]
/usr/lib/aconfmgr/main.bash:185 [Main]
/usr/lib/aconfmgr/main.bash:205 [Source]
/usr/bin/aconfmgr:26 [main]
$ _
```

**Comment by CyberShadow** [comment]
I think that points towards a problem with how your system is set up.

(Closing because the original problem was addressed.)

**Comment by Dieterbe** [comment]
Perhaps it would make sense to include the '/var/log/journal/*'" ignore rule by default?
After all, every arch user uses journald and in my case i saw a similar crash on my first run.  There may be other people who run into this issue and then just give up on the tool and don't come back.

We could add a comment explaining the issue, and people could still choose to remove the ignore rule if they wish to do so, but at least they'll know they might run into this.

Alternatively, perhaps aconfmgr could handle this case more gracefully (and ignore removed journald log files), although this would probably break the idempotency guarantee.  But that seems problematic on a live running system (that's writing and rotating logs) anyway.

**Comment by CyberShadow** [comment]
Yep, see #37... (Sorry, it's one of many things across many projects I want to improve!)

> BTW, this project looks awesome. I like the vision, the guiding principles (e.g. idempotency between save and apply commands) and the code is probably some of the cleanest shell script I've seen.

Thank you!
