### ISSUE TITLE
aconfmgr check doesn't check for incorrect CRLF characters

### ISSUE THREAD

**Issue by thecatwasnot** [CyberShadow/aconfmgr#94]
I accidentally got CRLF characters into my 10-ignores.sh file, `aconfmgr check` passed the file but the included IgnoreFile lines don't work.  Is this a bug?

**Comment by CyberShadow** [comment]
No, not as such. bash will interpret CR characters like any other characters, so the script will probably be understand as you wanting to ignore files whose name ends with a CR character.

Consider setting up ShellCheck in your editor, as it does warn on literal CR characters.

**Comment by thecatwasnot** [comment]
Good point on the Shell Check.  I suppose the problem was that I had CR characters where I didn't expect them and the IgnoreFile lines didn't work as expected.  Using ShellCheck (and getting my vimrc restored on this new system) would take care of the issue.
