### ISSUE TITLE
Too many found files - taking too long

### ISSUE THREAD

**Issue by jcguu95** [CyberShadow/aconfmgr#98]
After a fresh archlinux installation, and after installing some of my favorite packages (<100 packages). There are already ~220000 "found files", which seem to take >15 hours for a run. Is there any solution to this?

**Comment by CyberShadow** [comment]
Is this with a new configuration?

Have you tried adding some `IgnorePath` rules, as aconfmgr suggests in its output?

**Comment by jcguu95** [comment]
Yes, this is a new configuration - in that I haven't done much to my system after installing arch.

I didn't see in its output what I should ignore in order to drastically lessen the amount of files..

**Comment by CyberShadow** [comment]
The warning should look like:
```
Warning: reached 1000 lost files while in directory <dir>.
Perhaps add IgnorePath <dir> (or a parent directory) to configuration to ignore it.
```

Can you post the entire output?

**Comment by jcguu95** [comment]
Ah, that indeed resolve the problem. Thank you so much!
