### ISSUE TITLE
Filename-based ignores?

### ISSUE THREAD

**Issue by mmirate** [CyberShadow/aconfmgr#99]
Certain glob-patterns of filenames, regardless of what basedir contains them, are not relevant for backup/restore purposes. Examples: `__pycache__`, `lost+found`, `*-`, `*~`, `*.cache` and arguably `.*`. At any given time, they might be present at a multitude of full-paths on the system - hardcoding every one is impractical.

Any plans to add a more powerful version of IgnorePath that can handle this?

**Comment by CyberShadow** [comment]
`IgnorePath` syntax is that of `find -wholename`. I use something like the following for Python:

```bash
IgnorePath '/usr/lib/python3.8/__pycache__/*.pyc'
IgnorePath '/usr/lib/python3.8/*/__pycache__/*.pyc'
```
